// Japanese Hiragana, Katakana, and Kanji Database for Vocabulary App
const JAPANESE_DATABASE = {
    hiragana: [
        { char: 'あ', romaji: 'a', strokeCount: 3, memoryText: 'Kafasında anteni olan A harfi. Üzerinde bir A harfi bulunmaktadır. Bu sayede bu heceyi gördüğünüzde "A" hecesi olduğunu hatırlayabilirsiniz.', association: 'Anten / A Harfi' },
        { char: 'い', romaji: 'i', strokeCount: 2, memoryText: 'Yan yana duran 2 tane palmiye ağacı. Hawaii sözcüğünün sonundaki "ii" harfleri bize "i" hecesini hatırlatacak.', association: 'Palmiye Ağaçları' },
        { char: 'う', romaji: 'u', strokeCount: 2, memoryText: 'Geriye doğru gerilip "Uuuuu" diye bağıran adam silueti. Bu şekil bize "U" hecesini hatırlatacaktır.', association: 'Bağıran Adam' },
        { char: 'え', romaji: 'e', strokeCount: 2, memoryText: 'Koşu bandında egzersiz (E) yapan insan. Egzersiz sözcüğünden "E" hecesini hatırlayacağız.', association: 'Egzersiz' },
        { char: 'お', romaji: 'o', strokeCount: 3, memoryText: 'Otoban şeridi ve yanından geçen yol. "O"toban sözcüğü bize "O" hecesini hatırlatacaktır. "あ" harfine benzer ama sağ üst köşesinde otobandaki benzinci gibi ekstra bir çizgi vardır.', association: 'Otoban' },
        { char: 'か', romaji: 'ka', strokeCount: 3, memoryText: 'Kasabın elindeki et satırına benzer. "Ka"sap sözcüğünden "KA" hecesini hatırlayacağız.', association: 'Kasap Satırı' },
        { char: 'き', romaji: 'ki', strokeCount: 4, memoryText: 'Kilitleri açan bir anahtara benzer. Kilit sözcüğünden "Kİ" hecesini hatırlayacağız.', association: 'Kilit / Anahtar' },
        { char: 'く', romaji: 'ku', strokeCount: 1, memoryText: 'Sola doğru bakan kuş gagasına benzer. "Ku"ş sözcüğünden "KU" hecesini hatırlayacağız.', association: 'Kuş Gagası' },
        { char: 'け', romaji: 'ke', strokeCount: 3, memoryText: 'Döner kesen bıçak ve döner tezgahı. Kesmek sözcüğünden "KE" hecesini hatırlayacağız.', association: 'Döner / Kesmek' },
        { char: 'こ', romaji: 'ko', strokeCount: 2, memoryText: 'Yan yatmış bir kova siluetine benzer. Kova kelimesinden "KO" hecesini hatırlayacağız.', association: 'Kova' },
        { char: 'さ', romaji: 'sa', strokeCount: 3, memoryText: 'Salın üzerinde kürek çeken adam. "Sa"l kelimesini hatırlatır.', association: 'Sal' },
        { char: 'し', romaji: 'shi', strokeCount: 1, memoryText: 'Şemsiyenin ters tutulan sapı. "Şi"eklinde kıvrılmıştır.', association: 'Şemsiye' },
        { char: 'す', romaji: 'su', strokeCount: 2, memoryText: 'Su borusu sarmalı veya su damlası. "Su" kelimesini çağrıştırır.', association: 'Su Borusu' },
        { char: 'せ', romaji: 'se', strokeCount: 3, memoryText: 'Sırtı dayamalı sedir koltuk. "Se"dir kelimesini hatırlatır.', association: 'Sedir Koltuk' },
        { char: 'そ', romaji: 'so', strokeCount: 1, memoryText: 'Zikzak çizen solucan. "So"lucan.', association: 'Solucan' },
        { char: 'た', romaji: 'ta', strokeCount: 4, memoryText: 'Tahta levha üzerindeki yazı. "Ta"hta.', association: 'Tahta' },
        { char: 'ち', romaji: 'chi', strokeCount: 2, memoryText: 'Çinli şapkası takmış insan. "Çi"nli.', association: 'Çinli' },
        { char: 'つ', romaji: 'tsu', strokeCount: 1, memoryText: 'Büyük bir tsunami dalgası. "Tsu"nami.', association: 'Tsunami' },
        { char: 'て', romaji: 'te', strokeCount: 1, memoryText: 'Telefon ahizesi veya direği. "Te"lefon.', association: 'Telefon' },
        { char: 'と', romaji: 'to', strokeCount: 2, memoryText: 'Torba içine batan çivi. "To"rba.', association: 'Torba' },
        { char: 'な', romaji: 'na', strokeCount: 4, memoryText: 'Nal takan nalbant veya dua eden nalbant. "Na"lbant.', association: 'Nalbant' },
        { char: 'ni', romaji: 'ni', strokeCount: 3, memoryText: 'Dikey iğne ve yanındaki iplik. "Ni"dles (İğne).', association: 'İğne / İplik' },
        { char: 'ぬ', romaji: 'nu', strokeCount: 2, memoryText: 'Erişte noodle tabağı. Ucunda düğüm vardır. "Nu"dıl.', association: 'Noodle' },
        { char: 'ね', romaji: 'ne', strokeCount: 2, memoryText: 'Kuyruğu kıvrık bir kedi (Neko). "Ne"ko.', association: 'Kedi / Neko' },
        { char: 'の', romaji: 'no', strokeCount: 1, memoryText: 'Yasak levhası. Üzeri çizilmiş "No/Hayır".', association: 'Yasak İşareti' },
        { char: 'は', romaji: 'ha', strokeCount: 3, memoryText: 'Havan kabı ve ezme eli. "Ha"van.', association: 'Havan' },
        { char: 'ひ', romaji: 'hi', strokeCount: 1, memoryText: 'Gülümseyen bir ağız. "Hi"hihi diye güler.', association: 'Gülen Ağız' },
        { char: 'fu', romaji: 'fu', strokeCount: 4, memoryText: 'Flüt çalan müzisyen veya Fuji Dağı silueti. "Fu"ji.', association: 'Fuji Dağı / Flüt' },
        { char: 'へ', romaji: 'he', strokeCount: 1, memoryText: 'Havanın zirvesi, yokuş veya dağ tepesi. "He"yelan yokuşu.', association: 'Yokuş' },
        { char: 'ほ', romaji: 'ho', strokeCount: 4, memoryText: 'Horoz tüneği. "Ho"roz.', association: 'Horoz' },
        { char: 'ま', romaji: 'ma', strokeCount: 3, memoryText: 'Maskeli savaşçı yüzü. "Ma"ske.', association: 'Maske' },
        { char: 'み', romaji: 'mi', strokeCount: 2, memoryText: 'Müzik notası (21 sayısına benzer). "Mi" notası.', association: 'Müzik' },
        { char: 'む', romaji: 'mu', strokeCount: 3, memoryText: 'Boynuzlu inek kafası. "Muu" diye bağırır.', association: 'İnek' },
        { char: 'め', romaji: 'me', strokeCount: 2, memoryText: 'Noodle tabağındaki sade makarna. Düğümü yoktur. "Me"melodi makarnası.', association: 'Makarna' },
        { char: 'mo', romaji: 'mo', strokeCount: 3, memoryText: 'Denize atılmış olta iğnesi. Moby Dick balığı tutar. "Mo"by Dick.', association: 'Olta / Moby Dick' },
        { char: 'ya', romaji: 'ya', strokeCount: 3, memoryText: 'Yak öküzünün boynuzları. "Ya"k.', association: 'Yak Öküzü' },
        { char: 'ゆ', romaji: 'yu', strokeCount: 2, memoryText: 'Suda yüzen yunus balığı. "Yu"nus.', association: 'Yunus' },
        { char: 'よ', romaji: 'yo', strokeCount: 2, memoryText: 'Parmağa asılı yo-yo oyuncağı. "Yo"-yo.', association: 'Yo-yo' },
        { char: 'ら', romaji: 'ra', strokeCount: 2, memoryText: 'Ranzanın basamağı ve tavanı. "Ra"nza.', association: 'Ranza' },
        { char: 'り', romaji: 'ri', strokeCount: 2, memoryText: 'Ritim çizgileri. Sağdaki çizgi daha uzundur. "Ri"tim.', association: 'Ritim' },
        { char: 'る', romaji: 'ru', strokeCount: 1, memoryText: 'Ucu kıvrılmış rulo kağıt. "Ru"lo.', association: 'Rulo' },
        { char: 're', romaji: 're', strokeCount: 2, memoryText: 'Ayakta duran dik duruşlu reis veya yelkenli tekne. "Re"is.', association: 'Reis / Yelkenli' },
        { char: 'ろ', romaji: 'ro', strokeCount: 1, memoryText: 'Ucu düz kalan rulo kağıt (Düğümü yoktur). "Ro"ta rulosu.', association: 'Rota / Rulo' },
        { char: 'わ', romaji: 'wa', strokeCount: 2, memoryText: 'Kuyruğu içe bükük kuğu. "Va"tikan kuğusu.', association: 'Kuğu' },
        { char: 'を', romaji: 'wo/o', strokeCount: 3, memoryText: 'Volan çarkı veya direksiyon halkası. "Vo"lan.', association: 'Volan' },
        { char: 'ん', romaji: 'n', strokeCount: 1, memoryText: 'Latin N harfine benzer, tek başına durabilen tek sessiz harftir. "N" harfi.', association: 'N Harfi' },
        // Dakuten
        { char: 'が', romaji: 'ga', strokeCount: 5, memoryText: 'か (ka) harfinin yumuşatılmış hali.', association: 'Dakuten G' },
        { char: 'ぎ', romaji: 'gi', strokeCount: 6, memoryText: 'き (ki) harfinin yumuşatılmış hali.', association: 'Dakuten G' },
        { char: 'ぐ', romaji: 'gu', strokeCount: 3, memoryText: 'く (ku) harfinin yumuşatılmış hali.', association: 'Dakuten G' },
        { char: 'げ', romaji: 'ge', strokeCount: 5, memoryText: 'け (ke) harfinin yumuşatılmış hali.', association: 'Dakuten G' },
        { char: 'ご', romaji: 'go', strokeCount: 4, memoryText: 'こ (ko) harfinin yumuşatılmış hali.', association: 'Dakuten G' },
        { char: 'ざ', romaji: 'za', strokeCount: 5, memoryText: 'さ (sa) harfinin yumuşatılmış hali.', association: 'Dakuten Z' },
        { char: 'じ', romaji: 'ji', strokeCount: 3, memoryText: 'し (shi) harfinin yumuşatılmış hali.', association: 'Dakuten Z' },
        { char: 'ず', romaji: 'zu', strokeCount: 4, memoryText: 'す (su) harfinin yumuşatılmış hali.', association: 'Dakuten Z' },
        { char: 'ぜ', romaji: 'ze', strokeCount: 5, memoryText: 'せ (se) harfinin yumuşatılmış hali.', association: 'Dakuten Z' },
        { char: 'zo', romaji: 'zo', strokeCount: 3, memoryText: 'そ (so) harfinin yumuşatılmış hali.', association: 'Dakuten Z' },
        { char: 'だ', romaji: 'da', strokeCount: 6, memoryText: 'た (ta) harfinin yumuşatılmış hali.', association: 'Dakuten D' },
        { char: 'ぢ', romaji: 'ji', strokeCount: 4, memoryText: 'ち (chi) harfinin yumuşatılmış hali.', association: 'Dakuten D' },
        { char: 'づ', romaji: 'zu', strokeCount: 3, memoryText: 'つ (tsu) harfinin yumuşatılmış hali.', association: 'Dakuten D' },
        { char: 'de', romaji: 'de', strokeCount: 3, memoryText: 'て (te) harfinin yumuşatılmış hali.', association: 'Dakuten D' },
        { char: 'ど', romaji: 'do', strokeCount: 4, memoryText: 'と (to) harfinin yumuşatılmış hali.', association: 'Dakuten D' },
        { char: 'ば', romaji: 'ba', strokeCount: 5, memoryText: 'は (ha) harfinin yumuşatılmış hali.', association: 'Dakuten B' },
        { char: 'び', romaji: 'bi', strokeCount: 3, memoryText: 'ひ (hi) harfinin yumuşatılmış hali.', association: 'Dakuten B' },
        { char: 'ぶ', romaji: 'bu', strokeCount: 6, memoryText: 'ふ (fu) harfinin yumuşatılmış hali.', association: 'Dakuten B' },
        { char: 'be', romaji: 'be', strokeCount: 3, memoryText: 'へ (he) harfinin yumuşatılmış hali.', association: 'Dakuten B' },
        { char: 'ぼ', romaji: 'bo', strokeCount: 6, memoryText: 'ほ (ho) harfinin yumuşatılmış hali.', association: 'Dakuten B' },
        // Handakuten
        { char: 'ぱ', romaji: 'pa', strokeCount: 4, memoryText: 'は (ha) harfinin yuvarlak ile sertleştirilmiş hali.', association: 'Handakuten P' },
        { char: 'ぴ', romaji: 'pi', strokeCount: 2, memoryText: 'ひ (hi) harfinin yuvarlak ile sertleştirilmiş hali.', association: 'Handakuten P' },
        { char: 'ぷ', romaji: 'pu', strokeCount: 5, memoryText: 'ふ (fu) harfinin yuvarlak ile sertleştirilmiş hali.', association: 'Handakuten P' },
        { char: 'ぺ', romaji: 'pe', strokeCount: 2, memoryText: 'へ (he) harfinin yuvarlak ile sertleştirilmiş hali.', association: 'Handakuten P' },
        { char: 'ぽ', romaji: 'po', strokeCount: 5, memoryText: 'ほ (ho) harfinin yuvarlak ile sertleştirilmiş hali.', association: 'Handakuten P' }
    ],
    katakana: [
        { char: 'ア', romaji: 'a', strokeCount: 2, memoryText: 'Dar açılı keskin köşe. "A"çı.', association: 'Açı' },
        { char: 'イ', romaji: 'i', strokeCount: 2, memoryText: 'Yandan görünen yürüyen insan. "İ"nsan.', association: 'İnsan' },
        { char: 'ウ', romaji: 'u', strokeCount: 3, memoryText: 'Uçak gövdesi ve kanat ucu. "U"çak.', association: 'Uçak' },
        { char: 'エ', romaji: 'e', strokeCount: 3, memoryText: 'Ev direği veya çatı kirişi. "E"v.', association: 'Ev' },
        { char: 'オ', romaji: 'o', strokeCount: 3, memoryText: 'Kolları açık duran bir okçu. "O"kçu.', association: 'Okçu' },
        { char: 'カ', romaji: 'ka', strokeCount: 2, memoryText: 'Kanca veya çekme aleti. "Ka"nca.', association: 'Kanca' },
        { char: 'キ', romaji: 'ki', strokeCount: 3, memoryText: 'Kilit anahtarı (Hiragana gibi ama altı kavissizdir). "Ki"lit.', association: 'Kilit' },
        { char: 'ク', romaji: 'ku', strokeCount: 2, memoryText: 'Kukuletalı şapka veya külah. "Ku"kuleta.', association: 'Kukuleta' },
        { char: 'ケ', strokeCount: 3, romaji: 'ke', memoryText: 'Kemer tokası veya ucu. "Ke"mer.', association: 'Kemer' },
        { char: 'コ', romaji: 'ko', strokeCount: 2, memoryText: 'Ağzı açık köşe kutu. "Ko"ru kutusu.', association: 'Kutu' },
        { char: 'サ', romaji: 'sa', strokeCount: 3, memoryText: 'Sal tahtaları. "Sa"l.', association: 'Sal' },
        { char: 'シ', romaji: 'shi', strokeCount: 3, memoryText: 'Şelalenin aşağıdan yukarı sıçrayan suları. "Şi"elale.', association: 'Şelale' },
        { char: 'ス', romaji: 'su', strokeCount: 2, memoryText: 'Sürahinin kulpu ve ağzı. "Su"rahi.', association: 'Sürahi' },
        { char: 'セ', romaji: 'se', strokeCount: 2, memoryText: 'Modern sehpa. "Se"hpa.', association: 'Sehpa' },
        { char: 'ソ', romaji: 'so', strokeCount: 2, memoryText: 'Sola kayan solucan damlası. "So"lucan.', association: 'Solucan' },
        { char: 'タ', romaji: 'ta', strokeCount: 3, memoryText: 'Tarak sırtı. "Ta"rak.', association: 'Tarak' },
        { char: 'チ', romaji: 'chi', strokeCount: 3, memoryText: 'Çizgili yol veya işaretçi. "Çi"zgi.', association: 'Çizgi' },
        { char: 'ツ', romaji: 'tsu', strokeCount: 3, memoryText: 'Tsunami dalgası (Damlalar yukarıdan aşağı iner). "Tsu"nami.', association: 'Tsunami' },
        { char: 'テ', romaji: 'te', strokeCount: 3, memoryText: 'Tente veya çadır saçakları. "Te"nte.', association: 'Tente' },
        { char: 'ト', romaji: 'to', strokeCount: 2, memoryText: 'Totem direği dalı. "To"tem.', association: 'Totem' },
        { char: 'ナ', romaji: 'na', strokeCount: 2, memoryText: 'Nal asılan çivi. "Na"l.', association: 'Nal' },
        { char: 'ニ', romaji: 'ni', strokeCount: 2, memoryText: 'İki adet paralel tahta. Sayı "Ni" (İki).', association: 'İki' },
        { char: 'ヌ', romaji: 'nu', strokeCount: 2, memoryText: 'Noodle yiyen çubuklar. "Nu"dıl.', association: 'Noodle' },
        { char: 'ネ', romaji: 'ne', strokeCount: 4, memoryText: 'Nezle olmuş kedi kuyruğu. "Ne"zle kedisi.', association: 'Kedi' },
        { char: 'ノ', romaji: 'no', strokeCount: 1, memoryText: 'Eğik nokta veya çizgi. "No/Hayır" eğik şeridi.', association: 'Eğik Çizgi' },
        { char: 'ハ', romaji: 'ha', strokeCount: 2, memoryText: 'Havan ayakları veya çadır direkleri. "Ha"van.', association: 'Havan' },
        { char: 'ヒ', romaji: 'hi', strokeCount: 2, memoryText: 'Sola bakan hilal kaşık. "Hi"lal.', association: 'Hilal' },
        { char: 'フ', romaji: 'fu', strokeCount: 1, memoryText: 'Flüt ucu ve gerdanı. "Fu"lüt.', association: 'Flüt' },
        { char: 'ヘ', romaji: 'he', strokeCount: 1, memoryText: 'Yokuş yamaç (Hiragana gibidir). "He"yelan yokuşu.', association: 'Yokuş' },
        { char: 'ホ', romaji: 'ho', strokeCount: 4, memoryText: 'Horoz tüneği. "Ho"roz.', association: 'Horoz' },
        { char: 'マ', romaji: 'ma', strokeCount: 2, memoryText: 'Maske parçası. "Ma"ske.', association: 'Maske' },
        { char: 'ミ', romaji: 'mi', strokeCount: 3, memoryText: 'Üç ritim çizgisi. "Mi" ritmi.', association: 'Ritim' },
        { char: 'ム', romaji: 'mu', strokeCount: 2, memoryText: 'Boynuzlu inek burnu. "Muu" inek burnu.', association: 'İnek' },
        { char: 'メ', romaji: 'me', strokeCount: 2, memoryText: 'Çapraz keman yayları melodi. "Me"lodi.', association: 'Melodi' },
        { char: 'モ', romaji: 'mo', strokeCount: 3, memoryText: 'Olta kancası (Hiragana gibi ama köşelidir). "Mo"by Dick.', association: 'Olta' },
        { char: 'ヤ', romaji: 'ya', strokeCount: 2, memoryText: 'Yarım yak öküzü başı. "Ya"k.', association: 'Yak' },
        { char: 'ユ', romaji: 'yu', strokeCount: 2, memoryText: 'Yunus balığı sırt yüzgeci. "Yu"nus.', association: 'Yunus' },
        { char: 'ヨ', romaji: 'yo', strokeCount: 3, memoryText: 'Makaraya sarılmış yo-yo (Yatay E harfi gibi). "Yo"-yo.', association: 'Yo-yo' },
        { char: 'ラ', romaji: 'ra', strokeCount: 2, memoryText: 'Ranzanın üst kısmı. "Ra"nza.', association: 'Ranza' },
        { char: 'リ', romaji: 'ri', strokeCount: 2, memoryText: 'Ritim çizgileri (Hiragana gibidir). "Ri"tim.', association: 'Ritim' },
        { char: 'ル', romaji: 'ru', strokeCount: 2, memoryText: 'Rulo kağıt parçaları. "Ru"lo.', association: 'Rulo' },
        { char: 'レ', romaji: 're', strokeCount: 1, memoryText: 'Tek parça reis yelkeni. "Re"is.', association: 'Reis' },
        { char: 'ロ', romaji: 'ro', strokeCount: 3, memoryText: 'Kutu şeklinde rota çerçevesi. "Ro"ta kutusu.', association: 'Rota / Kutu' },
        { char: 'ワ', romaji: 'wa', strokeCount: 2, memoryText: 'Kuğu gagası ucu. "Va"tikan kuğusu.', association: 'Kuğu' },
        { char: 'ヲ', romaji: 'wo/o', strokeCount: 3, memoryText: 'Volan çarkı iki çizgisi. "Vo"lan.', association: 'Volan' },
        { char: 'ン', romaji: 'n', strokeCount: 2, memoryText: 'Yukarı kavisli solucan şeridi. "N" harfi.', association: 'N Harfi' },
        // Dakuten
        { char: 'ガ', romaji: 'ga', strokeCount: 4, memoryText: 'カ (ka) harfinin yumuşatılmış hali.', association: 'Dakuten G' },
        { char: 'ギ', romaji: 'gi', strokeCount: 5, memoryText: 'キ (ki) harfinin yumuşatılmış hali.', association: 'Dakuten G' },
        { char: 'グ', romaji: 'gu', strokeCount: 4, memoryText: 'ク (ku) harfinin yumuşatılmış hali.', association: 'Dakuten G' },
        { char: 'ゲ', romaji: 'ge', strokeCount: 5, memoryText: 'ケ (ke) harfinin yumuşatılmış hali.', association: 'Dakuten G' },
        { char: 'ゴ', romaji: 'go', strokeCount: 4, memoryText: 'コ (ko) harfinin yumuşatılmış hali.', association: 'Dakuten G' },
        { char: 'ザ', romaji: 'za', strokeCount: 5, memoryText: 'サ (sa) harfinin yumuşatılmış hali.', association: 'Dakuten Z' },
        { char: 'ジ', romaji: 'ji', strokeCount: 3, memoryText: 'シ (shi) harfinin yumuşatılmış hali.', association: 'Dakuten Z' },
        { char: 'ズ', romaji: 'zu', strokeCount: 4, memoryText: 'ス (su) harfinin yumuşatılmış hali.', association: 'Dakuten Z' },
        { char: 'ゼ', romaji: 'ze', strokeCount: 4, memoryText: 'セ (se) harfinin yumuşatılmış hali.', association: 'Dakuten Z' },
        { char: 'ゾ', romaji: 'zo', strokeCount: 3, memoryText: 'ソ (so) harfinin yumuşatılmış hali.', association: 'Dakuten Z' },
        { char: 'ダ', romaji: 'da', strokeCount: 5, memoryText: 'タ (ta) harfinin yumuşatılmış hali.', association: 'Dakuten D' },
        { char: 'ヂ', romaji: 'ji', strokeCount: 5, memoryText: 'チ (chi) harfinin yumuşatılmış hali.', association: 'Dakuten D' },
        { char: 'ヅ', romaji: 'zu', strokeCount: 4, memoryText: 'ツ (tsu) harfinin yumuşatılmış hali.', association: 'Dakuten D' },
        { char: 'デ', romaji: 'de', strokeCount: 5, memoryText: 'テ (te) harfinin yumuşatılmış hali.', association: 'Dakuten D' },
        { char: 'ド', romaji: 'do', strokeCount: 4, memoryText: 'ト (to) harfinin yumuşatılmış hali.', association: 'Dakuten D' },
        { char: 'バ', romaji: 'ba', strokeCount: 4, memoryText: 'ハ (ha) harfinin yumuşatılmış hali.', association: 'Dakuten B' },
        { char: 'ビ', romaji: 'bi', strokeCount: 4, memoryText: 'ヒ (hi) harfinin yumuşatılmış hali.', association: 'Dakuten B' },
        { char: 'ブ', romaji: 'bu', strokeCount: 3, memoryText: 'フ (fu) harfinin yumuşatılmış hali.', association: 'Dakuten B' },
        { char: 'ベ', romaji: 'be', strokeCount: 3, memoryText: 'へ (he) harfinin yumuşatılmış hali.', association: 'Dakuten B' },
        { char: 'ボ', romaji: 'bo', strokeCount: 6, memoryText: 'ホ (ho) harfinin yumuşatılmış hali.', association: 'Dakuten B' },
        // Handakuten
        { char: 'パ', romaji: 'pa', strokeCount: 3, memoryText: 'ハ (ha) harfinin yuvarlak ile sertleştirilmiş hali.', association: 'Handakuten P' },
        { char: 'ピ', romaji: 'pi', strokeCount: 3, memoryText: 'ヒ (hi) harfinin yuvarlak ile sertleştirilmiş hali.', association: 'Handakuten P' },
        { char: 'プ', romaji: 'pu', strokeCount: 2, memoryText: 'フ (fu) harfinin yuvarlak ile sertleştirilmiş hali.', association: 'Handakuten P' },
        { char: 'ペ', romaji: 'pe', strokeCount: 2, memoryText: 'へ (he) harfinin yuvarlak ile sertleştirilmiş hali.', association: 'Handakuten P' },
        { char: 'ポ', romaji: 'po', strokeCount: 5, memoryText: 'ホ (ho) harfinin yuvarlak ile sertleştirilmiş hali.', association: 'Handakuten P' }
    ],
    kanji: [
        { char: '一', romaji: 'ichi', meaning: 'Bir (Sayı)', strokeCount: 1, memoryText: 'Bir adet yatay çizgi. Bir sayısını temsil eder.', association: 'Bir Çizgi / Sayı 1' },
        { char: '二', romaji: 'ni', meaning: 'İki (Sayı)', strokeCount: 2, memoryText: 'İki adet yatay çizgi. İki sayısını temsil eder.', association: 'İki Çizgi / Sayı 2' },
        { char: '三', romaji: 'san', meaning: 'Üç (Sayı)', strokeCount: 3, memoryText: 'Üç adet yatay çizgi. Üç sayısını temsil eder.', association: 'Üç Çizgi / Sayı 3' },
        { char: '日', romaji: 'hi / nichi / jitsu', meaning: 'Güneş / Gün', strokeCount: 4, memoryText: 'Pencereli bir güneş resmi veya günleri gösteren bir takvim yaprağı.', association: 'Güneş / Takvim' },
        { char: '月', romaji: 'tsuki / getsu / gatsu', meaning: 'Ay (Gökyüzündeki)', strokeCount: 4, memoryText: 'Hilal şeklindeki gökyüzü ayı, ortasında iki bulut çizgisi vardır.', association: 'Hilal Ay' },
        { char: '木', romaji: 'ki / moku', meaning: 'Ağaç / Tahta', strokeCount: 4, memoryText: 'Dalları, gövdesi ve kökleri olan bir ağaç silueti.', association: 'Ağaç' },
        { char: '水', romaji: 'mizu / sui', meaning: 'Su', strokeCount: 4, memoryText: 'Ortada akan bir nehir şeridi, yanlarında su sıçramalarını gösteren damlalar.', association: 'Akan Su / Nehir' },
        { char: '火', romaji: 'hi / ka', meaning: 'Ateş', strokeCount: 4, memoryText: 'Yerde yanan bir odunun üzerindeki alev kıvılcımları.', association: 'Alevler' },
        { char: '人', romaji: 'hito / jin / nin', meaning: 'İnsan', strokeCount: 2, memoryText: 'İki bacağı üzerinde yürüyen bir insanın yandan görünüşü.', association: 'Yürüyen İnsan' },
        { char: '山', romaji: 'yama / san', meaning: 'Dağ', strokeCount: 3, memoryText: 'Üç adet zirvesi olan bir dağ silueti.', association: 'Üç Zirveli Dağ' }
    ]
};
